# Generated by Django 5.2.11 on 2026-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cacao Solo', 'Cacao Solo'), ('Barkada', 'Barkada'), ('Gift Pack', 'Gift Pack')], default='Cacao Solo', max_length=32),
        ),
    ]
